### ISSUE TITLE
WORKAROUND: two locations at same time

### ISSUE THREAD

**Issue by jwmaas** [zxdavb/evohome#10]
The current evohome setup (great work btw) allows choosing between two locations using "idx= 0 " or "idx=1". 
How to configure evohome if I want to use the two locations side by side?

I have tried two instances of evohome, I have tried "name:" and "friendly_name" and entering two "idx". None of these appear to get me two different locations. Both locations are accessible by changing the idx, however. Who has the solution?

**Comment by zxdavb** [comment]
> Who has the solution?

Sorry, no solution, the answer is that currently you can have only one location at once.  You can have any `idx` you like, though, not just 0 or 1.  If you use an invalid ordinal, it sets `idx` to 0.

I could add support for multiple accounts should there be sufficient demand, but I am concentrating on bug fixes until the component is accepted in HA.

There may be a quick work-around for this, I will give it a go & post back here...

**Beware**: having more than one location means you cannot have `high_precision` temperatures.   

There is a work-around for this by creating multiple supplementary accounts on https://international.mytotalconnectcomfort.com/Account.  Using the original account, that 'owns' all the locations, select `Account`, then `Grant User Access` to permit each one of your supplementary accounts to access one location only.

**Comment by zxdavb** [comment]
OK, this worked for me. You'll have to download the latest commit (which I posted 2 minutes ago).

Then shart a shell, and `cd` to the directory containing `custom_components` folder:
```python
cd custom_components
cp evohome.py evohome2.py
sed -i '/^DOMAIN/ s/evohome/evohome2/' evohome2.py

cd climate
cp evohome.py evohome2.py
sed -i '/^from/ s/evohome/evohome2/' evohome2.py
```
Then you'll need to add the following to your `configuration.yaml`:
```yaml
evohome:
  username: !secret evohome_username
  password: !secret evohome_password
  
evohome2:
  username: !secret evohome2_username
  password: !secret evohome2_password
```

I leave the rest fro you to figure out, but fro debugging, try:
```yaml
logger:
# default: warn
  logs:
    custom_components.evohome: debug
    custom_components.climate.evohome: debug
    custom_components.evohome2: debug
    custom_components.climate.evohome2: debug
```
