### ISSUE TITLE
Changes in 0.92 that prevent it starting?

### ISSUE THREAD

**Issue by Swiftnesses** [zxdavb/evohome#44]
It seems there's been some changes that prevents this loading in recent versions...

I read there's a change to components that means they need a manifest, will need to check more when I get home...

**Comment by Swiftnesses** [comment]
Got it: https://developers.home-assistant.io/docs/en/creating_integration_manifest.html

**Comment by zxdavb** [comment]
Hi,

Try this `bleeding_edge` version (which adds the manifest file) & let me know how you get on.  

The easiest way is to use a different URL for `custom_updater`:
```yaml
custom_updater:
# mode: storage
  hide_sensor: true
# show_installable: true
  track:
    - components
    - cards
  component_urls:
    - https://raw.githubusercontent.com/zxdavb/evohome/bleeding_edge/custom_components.json
#   - https://raw.githubusercontent.com/zxdavb/evohome/master/custom_components.json
```
