### ISSUE TITLE
custom_components/evohome/__init__.py (WARNING)

### ISSUE THREAD

**Issue by JamieP83** [zxdavb/evohome#47]
Hey,
love the addon! thank you :)

getting this error in my logs.

> hassbian on RPI4
> arch | armv7l
> -- | --
> dev | false
> docker | false
> hassio | false
> os_name | Linux
> python_version | 3.7.3
> timezone | UTC
> version | 0.95.4
> virtualenv | true

yaml

```
evohome:
  username: !secret EvoHomeUserName
  password: !secret EvoHomePassword

# These config parameters are presented with their default values...
# scan_interval: 300     # seconds, you might get away with 120
# high_precision: true   # temperature in tenths instead of halves
# location_idx: 0        # if you have more than 1 location, use this

# These config parameters are YMMV...
# use_heuristics: false  # this is for the highly adventurous person, YMMV
# use_schedules: false   # this is for the slightly adventurous person
# away_temp: 15.0        # °C, if you have a non-default Away temp
# off_temp: 5.0          # °C, if you have a non-default Heating Off temp
```

9:19 AM custom_components/evohome/__init__.py (WARNING)

> Log Details (WARNING)
> Fri Jul 05 2019 09:19:56 GMT+0100 (British Summer Time)
> available(4570297 [Home]) = False (debug code 0x02), self._status = {}, self._timers = {'statusUpdated': datetime.datetime(2019, 7, 5, 9, 19, 54, 732987)}
