### ISSUE TITLE
HCE80 UFC support

### ISSUE THREAD

**Issue by JvdBosch** [zxdavb/evohome#98]
Using a HGI80 and Home Assistant I'm trying to gain more insight. All seems well, but the heat demands of zones connected to the HCE80 controller stay unavailable (except the zone in which the evohome controller resides). What are the best practices to integrate the HCE80?

No actuator is visible:
```
schema:
  _name: Kantoor
  class: underfloor_heating
  sensor: "34:179717"
  actuators: []
```

And the value is unavailable:
![image](https://github.com/zxdavb/ramses_rf/assets/39052144/40d26169-6291-49bb-849c-a30c679d6ad9)

Any tips?
